### ISSUE TITLE
mutt文件夹编码问题

### ISSUE THREAD

**Issue by plokid** [Wjinlei/.dotfiles#1]
你好，我是在B站上看到你的mutt配置视频，自己试了一下，初qq邮箱外都没用配置成功，邮箱文件夹名是utf-7编码导致错误，重复mw文件中的获取文件名的命令
yeah邮箱
![图片](https://user-images.githubusercontent.com/72876162/211274524-adbdaea2-f814-47e0-8bd6-d1101b106240.png)
qq邮箱
![图片](https://user-images.githubusercontent.com/72876162/211275235-551a5f87-105f-4b59-a244-4d9b80452ee7.png)
没办法同步yeah邮箱的内容
![图片](https://user-images.githubusercontent.com/72876162/211275417-94dd5f9b-afe6-40d9-b128-8b9368ea678d.png)
请问有解决方法吗？

**Comment by Wjinlei** [comment]
看起来可能是你邮箱名的问题，这个邮箱名可能是可以改的，你看看你的邮箱设置有没有更改的地方，gmail是可以改的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wjinlei/.dotfiles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 下午5:22
收件人:&nbsp;"Wjinlei/.dotfiles"<&gt;;
***@***.***&gt;;
主题:&nbsp;[Wjinlei/.dotfiles] mutt文件夹编码问题 (Issue #1)





 
你好，我是在B站上看到你的mutt配置视频，自己试了一下，初qq邮箱外都没用配置成功，邮箱文件夹名是utf-7编码导致错误，重复mw文件中的获取文件名的命令
 yeah邮箱
 
 qq邮箱
 
 没办法同步yeah邮箱的内容
 
 请问有解决方法吗？

**Comment by plokid** [comment]
破案了，isync的问题，我去那边提去
